name: book_env
channels:
    - conda-forge
dependencies:
    - python=3.7
    - imbalanced-learn=0.4.3
    - jupyterlab=0.35.6
    - matplotlib=3.0.3
    - numpy=1.16.3
    - pandas=0.23.4
    - pandas-datareader=0.7.0
    - requests=2.21.0
    - pip
    - python-graphviz=0.10.1
    - scikit-learn=0.20.3
    - scipy=1.2.1
    - seaborn=0.9.0
    - sqlalchemy=1.3.3
    - statsmodels=0.9.0
    - pip:
        - git+https://github.com/stefmolin/login-attempt-simulator.git@pandas_book
        - git+https://github.com/stefmolin/ml-utils.git@pandas_book
        - git+https://github.com/stefmolin/stock-analysis.git@pandas_book
